services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2424"
      POSTGRES_DB: employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:2424@db:5432/employee_db
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
